### ISSUE TITLE
🐛 [Bug]: Button、Search、Input、InputNumber、InputIcon、Select等支持设置size的组件标准不一

### ISSUE THREAD

**Issue by linxiang07** [DevCloudFE/vue-devui#1199]
2022.10.5 更新

- [x] Button Finished by @vaebe on #1316
- [x] Search Finished by @vaebe on #1309
- [x] Input Finished by @vaebe on #1318
- [x] InputNumber Finished by @vaebe on #1216
- [x] Select Finished by @vaebe
- [x] Radio Finished by @vaebe on #1319
- [x] Checkbox Finished by @vaebe on #1321
- [x] AutoComplete Finished by @vaebe on #1324
- [x] DatePickerPro Finished by @vaebe
- [ ] Form 主要是修改 Form 中的表单组件
- [ ] Icon
- [ ] Pagination Finished by @vaebe
- [ ] Skeleton
- [x] Switch #1476
- [ ] Table
- [x] Tag Finished by @vaebe on #1335

---

### Version

v1.0.0-rc.11

### Vue Version

3.2.29

### Link to minimal reproduction

|               | xs      | sm         | md         | lg         |
| ------------- | ------- | ---------- | ---------- | ---------- |
| `Button`      | 20px      | 24px         | 32px         | 36px         |
| `Search`      | 无      | 26 px        | 32px         | 46px         |
| `Input`       | 无      | 24px         | 26px         | 44px         |
| `InputNumber` | 无      | 26px         | 28px         | 46px         |
| `InputIcon`   | 无demo? | 无demo?    | 无demo?    | 无demo?    |
| `Select`      | 无         | 22px         | 26px         | 42px         |
| `Radio`      | 28px         | 32px         | 36px         | 40px         |
| `Checkbox`      | 28px         | 32px         | 36px         | 40px         |
| `AutoComplete`      | 无         | 26px         | 32px         | 46px         |
| `DatePickerPro`      | 无         | 26px         | 28px         | 46px         |
| `Form`      | 无         | 待补充        | 待补充         | 待补充         |
| `Icon`      | 无         | 待补充        | 待补充         | 待补充         |
| `Pagination`      | 无         | 待补充        | 待补充         | 待补充         |
| `Skeleton`      | 无         | 待补充        | 待补充         | 待补充         |
| `Switch`      | 无         | 待补充        | 待补充         | 待补充         |
| `Table`      | 无         | 待补充        | 待补充         | 待补充         |
| `Tag`      | 无         | 待补充        | 待补充         | 待补充         |
| ant-design    |  无        | 24px         | 32px         | 40px         |
| Element-plus  |  无        | 与antd相同 | 与antd相同 | 与antd相同 |

### Step to reproduce

使用这些组件

### What is expected

1. 建议xs、 sm 、md、lg使用标准的尺寸
2. 建议这些将组件的尺寸使用公共的sass变量
3. 建议参考社区主流的尺寸
4. 考虑移除xs这个尺寸、或都都支持xs

### What is actually happening

大小不一，标准不同

**Comment by kagol** [comment]
赞成！

**Comment by vaebe** [comment]
是否可以考虑移除 md 把 md 直接作为默认

**Comment by kagol** [comment]
> 是否可以考虑移除 md 把 md 直接作为默认

md作为默认，但不移除比较合理，保留md可以显式表明默认到底是什么

**Comment by kagol** [comment]
建议将这三个尺寸抽成三个scss变量，统一使用，方便后续设计规范变更之后，修改起来方便。
```
$devui-size-sm: 24px;
$devui-size-md: 32px;
$devui-size-lg: 40px;
```

**Comment by vaebe** [comment]
2022-09-17
Button
Search
Input
InputNumber
Select
Radio
Checkbox
AutoComplete
DatePickerPro
Pagination
Tag 移除size xs类型

**Comment by vaebe** [comment]
Icon、Skeleton、Table 的size 属性应该是独立的吧 和表单没有关系 @linxiang07 @kagol

**Comment by hxj9102** [comment]
通过检查发现，
1. checkbox、select、switch组件中获取size的优先级顺序为from > group > props，与其他form组件的优先级顺序不一致，实际上应该是props > group > from比较合理。
2. input组件未设置默认样式为md，会影响html上没有默认size对应class。
看大佬在radio组件中修改了以上的问题，看下继续对上面组件进行修改，获取我这边修改后提pr也可以。 @vaebe

**Comment by vaebe** [comment]
> 通过检查发现，
> 
> 1. checkbox、select、switch组件中获取size的优先级顺序为from > group > props，与其他form组件的优先级顺序不一致，实际上应该是props > group > from比较合理。
> 2. input组件未设置默认样式为md，会影响html上没有默认size对应class。
>    看大佬在radio组件中修改了以上的问题，看下继续对上面组件进行修改，获取我这边修改后提pr也可以。 @vaebe
非常感谢

1. checkbox、switch 已经提pr了，select 还没看 大佬有时间可以修一下
2. input 没有 `.devui-input--md` 这个 class 和 scss 样式写的有关系，目前逻辑应该正确的。

**Comment by hxj9102** [comment]
> > 通过检查发现，
> > 
> > 1. checkbox、select、switch组件中获取size的优先级顺序为from > group > props，与其他form组件的优先级顺序不一致，实际上应该是props > group > from比较合理。
> > 2. input组件未设置默认样式为md，会影响html上没有默认size对应class。
> >    看大佬在radio组件中修改了以上的问题，看下继续对上面组件进行修改，获取我这边修改后提pr也可以。 @vaebe
> >    非常感谢
> 
> 1. checkbox、switch 已经提pr了，select 还没看 大佬有时间可以修一下
> 2. input 没有 `.devui-input--md` 这个 class 和 scss 样式写的有关系，目前逻辑应该正确的。

select已提pr

**Comment by vaebe** [comment]
#1493 #1492

**Comment by vaebe** [comment]
#1493

**Comment by vaebe** [comment]
#1493 #1492

**Comment by kagol** [comment]
Fixed by @linxiang07 @vaebe @hxj9102 🎉
