### ISSUE TITLE
✨ [Feature]: 完善组件单元测试

### ISSUE THREAD

**Issue by kagol** [DevCloudFE/vue-devui#947]
### What problem does this feature solve

为了保障组件质量和稳定性，为新特性的添加或代码重构添加防护网，每个组件需要增加完善的单元测试，测试组件的UI表现、交互逻辑是否正常，每个api是否生效和符合预期。

### What does the proposed API look like

执行以下命令可以查看全量组件的单元测试结果：
```
pnpm cli --filter vue-devui -- code-check -t unit-test
```

查看特定组件单元测试结果：
```
pnpm cli --filter vue-devui -- code-check -t unit-test -c alert,collapse
```

目前（2022.7.1）还有以下组件单元测试未完全通过，需要完善：
- [x] alert Finished by @linxiang07 on #1008 
- [x] collapse Finished by @linxiang07 on #1016 
- [x] date-picker-pro Finished by @daviForevel on #1082 
- [x] editable-select  Finished by @chenxi24 on #983 
- [x] form Finished by @linxiang07 on #1067 
- [x] image-preview Finished by @vaebe on #993  
- [x] layout Finished by @linxiang07 on #1023 
- [x] loading Finished by @linxiang07 on #1063  
- [x] modal Finished by @xingyan95  on #1074 
- [x] notification Finished by @linxiang07 on #1027 
- [x] overlay Finished by @xingyan95  on #1074 
- [x] pagination  Finished by @linxiang07 on #1067 
- [x] progress Finished by @linxiang07 on #1028 
- [x] rate Finished by @linxiang07 on #1029 
- [x] ripple Finished by @linxiang07 on #1030  
- [x] select 存在warn
- [x] skeleton Finished by @linxiang07 on #1031  
- [x] slider Finished by @linxiang07 on #1066  
- [x] splitter Finished by @linxiang07 on #1065  
- [x] statistic Finished by @linxiang07 on #1032  
- [x] status Finished by @linxiang07 on #1005 
- [x] switch 存在warn Finished by @linxiang07 on #1019 
- [x] tree Finished by @linxiang07 on #999

**Comment by kagol** [comment]
单元测试任务日志：
[https://github.com/DevCloudFE/vue-devui/runs/7145035717?check_suite_focus=true](https://github.com/DevCloudFE/vue-devui/runs/7145035717?check_suite_focus=true)

**Comment by daviForevel** [comment]
date-picker-pro  select 单测正在进行中

**Comment by xingyan95** [comment]
modal  overlay单测正在进行中

**Comment by kagol** [comment]
2022.7.18 update:
还有以下组件单元测试未通过：
- [ ] auto-complete
- [ ] date-picker-pro
- [ ] modal
- [ ] overlay
- [ ] pagination
- [ ] search
- [ ] select
- [ ] slider
- [ ] table
- [ ] time-picker
- [ ] time-select
- [ ] tree
- [ ] upload

**Comment by kagol** [comment]
2022.7.19 update:
还有以下组件单元测试未通过：
- [ ] date-picker-pro 还剩1个单测未通过
- [ ] search 还剩2个单测未通过
- [ ] select 还剩13个单测未通过
- [ ] tree 还剩1个单测未通过

**Comment by kagol** [comment]
2022.7.20 update:
还有以下组件单元测试未通过：
- [ ] tooltip 还剩2个单测未通过

```
 FAIL devui/tooltip/__tests__/tooltip.spec.tsx (8.541 s)
  d-tooltip
✓should render correctly (254 ms)
✓mouse enter delay & mouse leave delay (1042 ms)
✓tooltip disabled work (330 ms)
✕tooltip hide-after work (1429 ms)
✕mouse enter enterable (309 ms)
● d-tooltip › tooltip hide-after work
expect(received).toBeFalsy()
    Received: <div class="devui-flexible-overlay devui-tooltip" style="transform-origin: 50% calc(100% + 8px);"><span>tips text</span><div class="devui-flexible-overlay__arrow" /></div>
● d-tooltip › mouse enter enterable
expect(received).toBeFalsy()
    Received: <div class="devui-flexible-overlay devui-tooltip" style="transform-origin: 50% calc(100% + 8px);"><span>tips text</span><div class="devui-flexible-overlay__arrow" /></div>
Test Suites: 1 failed, 1 total
Tests:       2 failed, 3 passed, 5 total
```

**Comment by kagol** [comment]
2022.7.20 更新：
全部组件单元测试问题已由 @linxiang07 @xingyan95 @daviForevel 全部解决🎉🎉并将单元测试任务添加到 PR 门禁中。
但目前单元测试覆盖率还很低，还有大量测试用例未补齐，欢迎一起完善🤝🤝

**Comment by kagol** [comment]
d-select 存在一个 warn，会影响单元测试结果的查看：
```
    console.warn
      [Vue warn]: Maximum recursive updates exceeded in component <DSelect>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.
```

**Comment by kagol** [comment]
d-tooltip 偶先单测报错：
```
FAIL devui/tooltip/__tests__/tooltip.spec.tsx
  ● d-tooltip › mouse enter delay & mouse leave delay
    expect(received).toBeFalsy()
    Received: <div class="devui-flexible-overlay devui-tooltip" style="transform-origin: 50% calc(100% + 8px); top: -6px; left: 0px;"><span>tips text</span><div class="devui-flexible-overlay__arrow" style="bottom: -4px;" /></div>
      49 |       setTimeout(resolve, 500);
      50 |     });
    > 51 |     expect(document.querySelector(ns.b())).toBeFalsy();
         |                                            ^
      52 |     wrapper.unmount();
      53 |   });
      54 |
      at Object.<anonymous> (devui/tooltip/__tests__/tooltip.spec.tsx:51:44)
Test Suites: 1 failed, 85 passed, 86 total
Tests:       1 failed, 1 todo, 510 passed, 512 total
Snapshots:   1 passed, 1 total
```

**Comment by kagol** [comment]
d-tooltip 偶现单测报错：
```
Summary of all failing tests
FAIL devui/tooltip/__tests__/tooltip.spec.tsx
  ● d-tooltip › tooltip hide-after work

    expect(received).toBeTruthy()

    Received: null

      107 |     });
      108 |     const tooltipContent = document.querySelector(ns.b());
    > 109 |     expect(tooltipContent).toBeTruthy();
          |                            ^
      110 |     await btn.trigger('mouseleave');
      111 |     await new Promise((resolve) => {
      112 |       setTimeout(resolve, 100);

      at Object.<anonymous> (devui/tooltip/__tests__/tooltip.spec.tsx:109:28)

  ● d-tooltip › mouse enter enterable

    expect(received).toBeFalsy()

    Received: <div class="devui-flexible-overlay devui-tooltip" style="transform-origin: 50% calc(100% + 8px); top: -6px; left: 0px;"><span>tips text</span><div class="devui-flexible-overlay__arrow" style="bottom: -4px;" /></div>

      [166](https://github.com/DevCloudFE/vue-devui/runs/7611310212?check_suite_focus=true#step:8:167) |     tooltip.dispatchEvent(evt);
      [167](https://github.com/DevCloudFE/vue-devui/runs/7611310212?check_suite_focus=true#step:8:168) |     await nextTick();
    > [168](https://github.com/DevCloudFE/vue-devui/runs/7611310212?check_suite_focus=true#step:8:169) |     expect(document.querySelector(ns.b())).toBeFalsy();
          |                                            ^
      [169](https://github.com/DevCloudFE/vue-devui/runs/7611310212?check_suite_focus=true#step:8:170) |
      [170](https://github.com/DevCloudFE/vue-devui/runs/7611310212?check_suite_focus=true#step:8:171) |     wrapper.unmount();
      [171](https://github.com/DevCloudFE/vue-devui/runs/7611310212?check_suite_focus=true#step:8:172) |   });

      at Object.<anonymous> (devui/tooltip/__tests__/tooltip.spec.tsx:168:44)


Test Suites: 1 failed, 86 passed, 87 total
Tests:       2 failed, 1 todo, 514 passed, 517 total
Snapshots:   1 passed, 1 total
```
